---
- name: Manage Ansible Tower Projects
  block:

    - when: tower_projects is not defined
      name: Check tower_projects is defined
      debug:
        msg: tower_projects not defined - no further action from role

    - when: tower_projects is defined
      name: "Manage Ansible Tower projects state"
      tower_project:
        name:                 "{{ project.name }}"
        description:          "{{ project.description           | default('No description') }}"
        organization:         "{{ project.organization          | default('Default') }}"
        scm_url:              "{{ project.scm_url }}"
        scm_type:             "{{ project.scm_type              | default('git') }}"
        scm_credential:       "{{ project.scm_credential        | default(omit) }}"
        scm_branch:           "{{ project.scm_branch            | default(omit) }}"
        scm_update_on_launch: "{{ project.scm_update_on_launch  | default('false') }}"
        state:                "{{ projct.state                  | default('present') }}"
        tower_host:           "{{ tower_hostname                | default(omit) }}"  
        tower_username:       "{{ tower_username                | default(omit) }}"
        tower_password:       "{{ tower_admin_password          | default(omit) }}"
        tower_verify_ssl:     "{{ tower_verify_ssl              | default(false) }}"
      loop: "{{ tower_projects }}"
      loop_control:
        loop_var: project

    - name: Pause to allow Ansible Tower Projects to populate
      wait_for:
        timeout: 40
  tags:
    - tower-projects-create
    - tower-projects-delete
    - tower-projects-manage
    - tower-projects
...
